import data.types.EpicTask;
import data.types.SubTask;
import data.types.Task;
import data.types.TaskStatus;
import servises.TaskManager;

public class Main {

    public static void main(String[] args) {
        TaskManager taskManager = new TaskManager();
        taskManager.createNewTask(new Task("new", "newDescription", TaskStatus.NEW));
        taskManager.createNewEpic(new EpicTask("Переезд", "epic1"));
        taskManager.createSubTask(new SubTask("Собрать коробки", "sub1", TaskStatus.NEW, 2));
        taskManager.createSubTask(new SubTask("Упаковать кошку", "sub2", TaskStatus.NEW, 2));
        taskManager.createSubTask(new SubTask("Сказать слова прощания", "sub3", TaskStatus.NEW, 2));
        taskManager.createNewEpic(new EpicTask("Важный эпик 2", "epic1"));
        taskManager.createSubTask(new SubTask("Задача 1", "sub1", TaskStatus.NEW, 6));
        taskManager.createSubTask(new SubTask("Задача 1", "sub2", TaskStatus.NEW, 6));
        taskManager.createNewEpic(new EpicTask("Важный эпик 2", "epic1"));
        taskManager.createSubTask(new SubTask("Задача 1", "sub1", TaskStatus.DONE, 9));
        taskManager.createSubTask(new SubTask("Задача 1", "sub2", TaskStatus.NEW, 9));
        System.out.println(taskManager.getTasksList());
        System.out.println(taskManager.getEpicTasksList());
        System.out.println(taskManager.getSubTasksList());
        taskManager.deleteSubTaskByID(10);
        System.out.println(taskManager.getEpicTasksList());
        System.out.println(taskManager.getSubTasksList());
        taskManager.deleteEpicTaskByID(6);
        System.out.println(taskManager.getEpicTasksList());
        System.out.println(taskManager.getSubTasksList());
        System.out.println(taskManager.getSubTasksListOfEpicByID(2));
        taskManager.createNewTask(new Task("new", "newDescription", TaskStatus.NEW));
        taskManager.createNewEpic(new EpicTask("Переезд", "epic1"));
        taskManager.createSubTask(new SubTask("Собрать коробки", "sub1", TaskStatus.NEW, 13));
        taskManager.createSubTask(new SubTask("Упаковать кошку", "sub2", TaskStatus.NEW, 13));
        taskManager.createSubTask(new SubTask("Сказать слова прощания", "sub3", TaskStatus.NEW, 13));
        taskManager.createNewEpic(new EpicTask("Важный эпик 2", "epic1"));
        taskManager.createSubTask(new SubTask("Задача 1", "sub1", TaskStatus.NEW, 17));
        taskManager.createSubTask(new SubTask("Задача 12", "sub2", TaskStatus.NEW, 17));
        taskManager.createNewEpic(new EpicTask("Важный эпик 2", "epic1"));
        taskManager.createSubTask(new SubTask("Задача 13", "sub1", TaskStatus.DONE, 20));
        taskManager.createSubTask(new SubTask("Задача 14", "sub2", TaskStatus.NEW, 13));
        System.out.println(taskManager.getTasksList());
        System.out.println(taskManager.getEpicTasksList());
        System.out.println(taskManager.getSubTasksList());
        taskManager.deleteAllTasks();
        taskManager.deleteAllEpics();
        System.out.println(taskManager.getTasksList());
        System.out.println(taskManager.getEpicTasksList());
        System.out.println(taskManager.getSubTasksList());
        taskManager.createNewTask(new Task("new", "newDescription", TaskStatus.NEW));
        taskManager.createNewEpic(new EpicTask("Переезд", "epic1"));
        taskManager.createSubTask(new SubTask("Собрать коробки", "sub1", TaskStatus.NEW, 24));
        taskManager.createSubTask(new SubTask("Упаковать кошку", "sub2", TaskStatus.NEW, 24));
        taskManager.createSubTask(new SubTask("Сказать слова прощания", "sub3", TaskStatus.NEW, 24));
        taskManager.createNewEpic(new EpicTask("Важный эпик 2", "epic1"));
        taskManager.createSubTask(new SubTask("Задача 1", "sub1", TaskStatus.NEW, 28));
        taskManager.createSubTask(new SubTask("Задача 1", "sub2", TaskStatus.NEW, 28));
        taskManager.createNewEpic(new EpicTask("Важный эпик 2", "epic1"));
        taskManager.createSubTask(new SubTask("Задача 1", "sub1", TaskStatus.DONE, 31));
        taskManager.createSubTask(new SubTask("Задача 1", "sub2", TaskStatus.NEW, 31));
        taskManager.deleteAllSubs();
        System.out.println(taskManager.getTasksList());
        System.out.println(taskManager.getEpicTasksList());
        System.out.println(taskManager.getSubTasksList());
        taskManager.createSubTask(new SubTask("Задача 1", "sub1", TaskStatus.DONE, 31));
        taskManager.createSubTask(new SubTask("Задача 1", "sub2", TaskStatus.NEW, 31));
        taskManager.createSubTask(new SubTask("Задача 1", "sub1", TaskStatus.NEW, 28));
        taskManager.createSubTask(new SubTask("Задача 1", "sub2", TaskStatus.NEW, 28));
        taskManager.deleteTaskByID(23);
        taskManager.deleteSubTaskByID(34);
        taskManager.deleteEpicTaskByID(28);
        taskManager.createNewTask(new Task("new", "newDescription", TaskStatus.NEW));
        taskManager.createNewTask(new Task("new", "newDescription", TaskStatus.NEW));
        System.out.println(taskManager.getTasksList());
        System.out.println(taskManager.getEpicTasksList());
        System.out.println(taskManager.getSubTasksList());
        taskManager.refreshTask(new Task("notNew", "blablabla", TaskStatus.IN_PROGRESS), 38);
        taskManager.refreshEpicTask(new EpicTask("notNewEpic", "trololo"), 24);
        taskManager.refreshSubTask(new SubTask("notNewSub", "dykdatakidyk", TaskStatus.DONE, 24), 35);
        System.out.println(taskManager.getTasksList());
        System.out.println(taskManager.getEpicTasksList());
        System.out.println(taskManager.getSubTasksList());
    }
}
